export const mockChats = [
  {
    id: "1",
    name: "Sarah Johnson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    lastMessage: "See you tomorrow! 👋",
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 min ago
    unreadCount: 0,
    isActive: true,
    lastMessageRead: true,
    isVoiceMessage: false,
  },
  {
    id: "2",
    name: "Design Team",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=design",
    lastMessage: "Design review tomorrow at 10 AM",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    unreadCount: 3,
    isActive: false,
    lastMessageRead: false,
    isVoiceMessage: false,
  },
  {
    id: "3",
    name: "Alex Chen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    lastMessage: "🎵",
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    unreadCount: 0,
    isActive: true,
    lastMessageRead: true,
    isVoiceMessage: true,
  },
  {
    id: "4",
    name: "Project Alpha",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alpha",
    lastMessage: "Great work on the last update!",
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    unreadCount: 5,
    isActive: false,
    lastMessageRead: false,
    isVoiceMessage: false,
  },
  {
    id: "5",
    name: "Marketing Sync",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marketing",
    lastMessage: "Campaign metrics looking good",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    unreadCount: 0,
    isActive: false,
    lastMessageRead: true,
    isVoiceMessage: false,
  },
  {
    id: "6",
    name: "Marketing Sync",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marketing",
    lastMessage: "Campaign metrics looking good",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    unreadCount: 0,
    isActive: false,
    lastMessageRead: true,
    isVoiceMessage: false,
  },
  {
    id: "7",
    name: "Marketing Sync",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marketing",
    lastMessage: "Campaign metrics looking good",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    unreadCount: 0,
    isActive: false,
    lastMessageRead: true,
    isVoiceMessage: false,
  },
  {
    id: "8",
    name: "Marketing Sync",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marketing",
    lastMessage: "Campaign metrics looking good",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    unreadCount: 0,
    isActive: false,
    lastMessageRead: true,
    isVoiceMessage: false,
  },
  {
    id: "9",
    name: "Marketing Sync",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marketing",
    lastMessage: "Campaign metrics looking good",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    unreadCount: 0,
    isActive: false,
    lastMessageRead: true,
    isVoiceMessage: false,
  },
  {
    id: "10",
    name: "Marketing Sync",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marketing",
    lastMessage: "Campaign metrics looking good",
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    unreadCount: 0,
    isActive: false,
    lastMessageRead: true,
    isVoiceMessage: false,
  },
];

export const mockMessages = [
  {
    id: "1",
    sender: "Sarah Johnson",
    content: "Hi! How are you doing?",
    timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    isRead: true,
    hasReactions: true,
    reactions: [{ emoji: "👋", count: 1 }],
  },
  {
    id: "2",
    sender: "user",
    content: "Hey! I'm doing great, thanks for asking! How about you?",
    timestamp: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
    isRead: true,
    hasReactions: false,
    reactions: [],
  },
  {
    id: "3",
    sender: "Sarah Johnson",
    content: "Doing well! Just finished the project we were working on",
    timestamp: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    isRead: true,
    hasReactions: false,
    reactions: [],
  },
  {
    id: "4",
    sender: "Sarah Johnson",
    content: "Want to grab coffee later?",
    timestamp: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
    isRead: true,
    hasReactions: true,
    reactions: [{ emoji: "☕", count: 1 }],
  },
  {
    id: "5",
    sender: "user",
    content: "That sounds amazing! What time?",
    timestamp: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    isRead: true,
    hasReactions: false,
    reactions: [],
  },
  {
    id: "6",
    sender: "Sarah Johnson",
    content: "How about 3 PM at our usual spot?",
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    isRead: true,
    hasReactions: false,
    reactions: [],
  },
  {
    id: "7",
    sender: "user",
    content: "Perfect! See you then 😊",
    timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    isRead: true,
    hasReactions: true,
    reactions: [{ emoji: "😊", count: 1 }],
  },
  {
    id: "8",
    sender: "Sarah Johnson",
    content: "See you tomorrow! 👋",
    timestamp: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    isRead: false,
    hasReactions: false,
    reactions: [],
  },
];

export const mockReactions = ["😊", "❤️", "😂", "😮", "😢", "🔥", "👍", "🎉"];
